services:
  phev2mqtt:
    image: ghcr.io/stefanh12/phev2mqtt:latest
    container_name: phev2mqtt
    environment:
      - mqtt_server=${MQTT_SERVER:-192.168.1.2:1883}
      - mqtt_user=${MQTT_USER:-phevmqttuser}
      - mqtt_password=${MQTT_PASSWORD}
      - phev_register=${PHEV_REGISTER:-false}
      - debug=${DEBUG:-false}
      - route_add=${ROUTE_ADD:-192.168.1.1}
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    restart: unless-stopped
